// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgzhlooyfDirhNsYww63URZfMhhl2DDhE',
    appId: '1:1080961954717:web:b681c3466cac60d704f574',
    messagingSenderId: '1080961954717',
    projectId: 'baseer-40cf2',
    authDomain: 'baseer-40cf2.firebaseapp.com',
    databaseURL: 'https://baseer-40cf2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'baseer-40cf2.firebasestorage.app',
    measurementId: 'G-CZFNNZ6627',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM7BTnOFvRuA2ZO5uf5g9YxJlTr-6zBOE',
    appId: '1:1080961954717:android:f2a307fba232295604f574',
    messagingSenderId: '1080961954717',
    projectId: 'baseer-40cf2',
    databaseURL: 'https://baseer-40cf2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'baseer-40cf2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeKAEnjpj-x--TElE7LCUojPyKlUm_WGk',
    appId: '1:1080961954717:ios:d1a04e690feb923104f574',
    messagingSenderId: '1080961954717',
    projectId: 'baseer-40cf2',
    databaseURL: 'https://baseer-40cf2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'baseer-40cf2.firebasestorage.app',
    iosBundleId: 'com.example.basser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeKAEnjpj-x--TElE7LCUojPyKlUm_WGk',
    appId: '1:1080961954717:ios:d1a04e690feb923104f574',
    messagingSenderId: '1080961954717',
    projectId: 'baseer-40cf2',
    databaseURL: 'https://baseer-40cf2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'baseer-40cf2.firebasestorage.app',
    iosBundleId: 'com.example.basser',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgzhlooyfDirhNsYww63URZfMhhl2DDhE',
    appId: '1:1080961954717:web:b415f4107c08f79204f574',
    messagingSenderId: '1080961954717',
    projectId: 'baseer-40cf2',
    authDomain: 'baseer-40cf2.firebaseapp.com',
    databaseURL: 'https://baseer-40cf2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'baseer-40cf2.firebasestorage.app',
    measurementId: 'G-Z6WK83LV7H',
  );
}
